version: '2'
volumes:
  postgres:


services:
  postgres:
    image: postgres:9.6
    ports:
      - "5438:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=taskmaster
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskmaster
