name: Tests
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-lein-2.9.1
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: taskmaster
          POSTGRES_PASSWORD: password
          POSTGRES_DB: taskmaster
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Cache Clojure deps
      uses: actions/cache@v1
      with:
        path: /root/.m2
        key: v1-deps-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          v1-deps-
          v1-deps-${{ hashFiles('**/project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test 2>&1
      env:
        PG_HOST: postgres
        PG_PORT: 5432
        PG_NAME: taskmaster_test
